---
title: "Clonotype Analysis"
author: "Kent Riemondy RBI"
date: "1/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash, eval = FALSE}
BIN="/usr/local/bin"
DBASES="$HOME/Projects/sc_repos/eickelberg/dbases"
run_changeo () {
  outfile=$1
  outfile_prefix=${outfile/.txz/}
  echo $outfile
  $BIN/AssignGenes.py \
    igblast \
    -s $1 \
    -b ~/share/igblast \
    --organism mouse \
    --loci ig \
    --format blast \
    --nproc 6
    
  $BIN/MakeDb.py igblast \
    -i ${outfile/.fasta/_igblast.fmt7} \
    -s $1 \
    -r ~/share/germlines/imgt/mouse/vdj/imgt_mouse_*.fasta \
    --10x $2 
    
  $BIN/ParseDb.py split \
    -d ${outfile/.fasta/_igblast_db-pass.tab} \
    -f FUNCTIONAL
  
  $BIN/ParseDb.py select \
    -d ${outfile/.fasta/_igblast_db-pass_FUNCTIONAL-T.tab} \
    -f LOCUS -u "IGH" \
    --logic all --regex --outname heavy
    
  $BIN/ParseDb.py select \
    -d ${outfile/.fasta/_igblast_db-pass_FUNCTIONAL-T.tab} \
    -f LOCUS -u "IG[LK]" \
    --logic all --regex --outname light
        
  
}

for sample in B6_B6_171501_Bcell HLA_B6_163107_Bcell HLA_B6_168467_Bcell NaiveB6_Bcell
do 
  echo $sample
  run_changeo \
    "../../data/vdj/"$sample"/outs/filtered_contig.fasta" \
    "../../data/vdj/"$sample"/outs/filtered_contig_annotations.csv"
  
done

```


```{r}
library(alakazam)
library(shazam)
library(tigger)
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())

outdir <- "vdj_alone"
```

```{r}
samples <- c(
  B6_B6 = "B6_B6_171501_Bcell", 
  HLA_B6_1 = "HLA_B6_163107_Bcell", 
  HLA_B6_2 = "HLA_B6_168467_Bcell", 
  Naive_B6 = "NaiveB6_Bcell")

co_paths <- file.path(
  "..",
  "..",
  "data",
  "vdj",
  samples,
  "outs",
  "heavy_parse-select.tab"
)

names(co_paths) <- names(samples)

co <- map(co_paths, ~readChangeoDb(.x, 
                                   select = NULL, 
                                   drop = NULL, 
                                   seq_upper = TRUE))

co <- bind_rows(co, .id = "SAMPLE")
```

Remove cells with > 1 heavy chain

```{r}
co <- group_by(co, CELL) %>% 
  mutate(n = n()) %>% 
  filter(n == 1) %>% 
  select(-n)

```

Get amino acid info
```{r}
co <- ungroup(co)
co <- aminoAcidProperties(co, seq = "JUNCTION", nt = TRUE, trim = FALSE, label = "CDR3")
co$CDR3_AA <- translateDNA(co$JUNCTION, trim=FALSE)
```

```{r}
dist_ham <- distToNearest(co, vCallColumn="V_CALL", 
                          model="ham", normalize="len", nproc=1, 
                          fields = "SAMPLE", first = FALSE)
dist_aa <- distToNearest(co, vCallColumn="V_CALL", 
                          model="aa", normalize="len", nproc=1, fields = "SAMPLE", 
                         first = FALSE)

dist_s1f <- distToNearest(co, vCallColumn="V_CALL", 
                          model="mk_rs1nf", normalize="none", nproc=1, fields = "SAMPLE",
                          first = FALSE)

p1 <- ggplot(filter(dist_ham, !is.na(DIST_NEAREST)),
             aes(x=DIST_NEAREST)) + 
    theme_bw() + 
    xlab("Hamming distance") + 
    ylab("Count") +
    scale_x_continuous(breaks=seq(0, 1, 0.1)) +
    geom_histogram(color="white", binwidth=0.02) +
  facet_grid(SAMPLE ~ ., scales="free_y") +
  labs(title = "Hamming distance (nt)")

p2 <- ggplot(filter(dist_aa, !is.na(DIST_NEAREST)),
             aes(x=DIST_NEAREST)) + 
    theme_bw() + 
    xlab("Hamming distance") + 
    ylab("Count") +
    scale_x_continuous(breaks=seq(0, 1, 0.1)) +
    geom_histogram(color="white", binwidth=0.02) +
  facet_grid(SAMPLE ~ ., scales="free_y") +
  labs(title = "Hamming distance (aa)")

 
p4 <- ggplot(filter(dist_s1f, !is.na(DIST_NEAREST)),
             aes(x=DIST_NEAREST)) + 
    theme_bw() + 
    xlab("Hamming distance") + 
    ylab("Count") +
  #  scale_x_continuous(breaks=seq(0, 1, 0.1)) +
    geom_histogram(color="white", binwidth=1) +
  facet_grid(SAMPLE ~ ., scales="free_y") +
  labs(title = "Human heavy chain, silent, 1-mer, functional substitution model")


plt <- plot_grid(p1, p2, p4, nrow = 1, ncol = 3)
plt
save_plot(file.path(outdir, "repertoire_distances.pdf"), plt, nrow = 1, ncol = 3)
```

```{r}
library("scoper")
co_per_sample <- split(co, co$SAMPLE)

res <- map(co_per_sample,
           ~defineClonesScoper(db = .x,
                   model = "hierarchical",
                   method = "complete",
                   germline_col = "GERMLINE_IMGT", 
                   sequence_col = "SEQUENCE_IMGT",
                   junction_col = "JUNCTION", 
                   v_call_col = "V_CALL", 
                   j_call_col = "J_CALL",
                   clone_col = "clone_id",
                   targeting_model = NULL, len_limit = NULL, first = TRUE, 
                   cdr3 = FALSE, mod3 = FALSE, max_n = NULL, threshold = 0.10,
                   base_sim = 0.95, iter_max = 1000, nstart = 1000, nproc = 1,
                   verbose = FALSE, log_verbose = FALSE, out_dir = ".",
                   summerize_clones = TRUE))

p <- map(res,~.x$plot_inter_intra) %>% 
  plot_grid(plotlist = ., labels = names(res), 
            nrow = 4, ncol = 1) 

save_plot(file.path(outdir, "clonal_distances.pdf"), 
          p,
          nrow = 4, ncol = 1, base_asp = 1.4)

res_combined <- defineClonesScoper(db = co,
                   model = "hierarchical",
                   method = "complete",
                   germline_col = "GERMLINE_IMGT", 
                   sequence_col = "SEQUENCE_IMGT",
                   junction_col = "JUNCTION", 
                   v_call_col = "V_CALL", 
                   j_call_col = "J_CALL",
                   clone_col = "clone_id",
                   targeting_model = NULL, len_limit = NULL, first = TRUE, 
                   cdr3 = FALSE, mod3 = FALSE, max_n = NULL, threshold = 0.10,
                   base_sim = 0.95, iter_max = 1000, nstart = 1000, nproc = 1,
                   verbose = FALSE, log_verbose = FALSE, out_dir = ".",
                   summerize_clones = TRUE)


res_combined_simple <- res_combined$db %>% 
  group_by(clone_id) %>% 
  mutate(
    clone_size = n(),
    convergent = length(unique(SAMPLE)) > 1) %>% 
  ungroup() %>% 
  select(SAMPLE, CELL, 
         all_sample_clone_id = clone_id, 
         all_sample_clone_size = clone_size, convergent)

```

```{r}
p <- imap(res, function(x, y){
  table(x$db$clone_id) %>% 
    as.data.frame() %>% 
    arrange(desc(Freq)) %>% 
    slice(1:50) %>% 
    mutate(Var1 = factor(Var1, levels = Var1)) %>% 
    ggplot(aes(Var1, Freq)) + 
    geom_col() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    labs(title = y,
         x = "new_clonotype_id",
         y = "Frequency")
}) %>% 
  plot_grid(plotlist = .,
            nrow = 4, 
            ncol = 1) 

p 
save_plot(file.path(outdir, "new_clonotype_frequencies.pdf"),
          p,
          nrow = 4, 
          ncol = 1,
          base_asp = 2.0)
```

```{r}
map_dfr(res, ~table(.x$db$clone_id) %>% 
      as.data.frame() %>%
      summarize(n_clonal = sum(Freq > 1),
                prop_clonal = n_clonal / n()), .id = "SAMPLE")

```


```{r}
co_out <- map_dfr(res, ~.x$db)

co_out <- mutate(co_out, 
                 cell_id = str_remove(CELL, "-1$"),
                 tmp_sample = case_when(
                   SAMPLE == "B6_B6" ~ "B6B6_6",
                   SAMPLE == "HLA_B6_1" ~"HLAB6_6",
                   SAMPLE == "HLA_B6_2" ~"HLAB6_7",
                   SAMPLE == "Naive_B6" ~ "Naive_B6"),
                 cell_id = str_c(tmp_sample, "_", cell_id)) %>% 
   group_by(cell_id) %>%
  mutate(n = n()) %>% 
  filter(n == 1) %>% 
  group_by(SAMPLE, clone_id) %>% 
  mutate(clone_size = n()) %>% 
  select(-tmp_sample, -n)

# add in convergent clone info
co_out <- ungroup(co_out) %>% 
  left_join(res_combined_simple, by = c("SAMPLE", "CELL"))


write_tsv(co_out, file.path(outdir, "vdj_new_clones.tsv.gz"))

```


```{r}
library(circlize)
mat <- filter(co_out, convergent) %>% 
  group_by(SAMPLE, all_sample_clone_id) %>% 
  mutate(n = n()) %>%
  select(SAMPLE, all_sample_clone_id, n) %>% 
  unique() %>% 
  pivot_wider(names_from = SAMPLE, 
              values_from = n,
              values_fill = list(n = 0)) %>% 
  column_to_rownames("all_sample_clone_id") %>% 
  as.matrix() %>% 
  t()

df = data.frame(from = rep(rownames(mat), times = ncol(mat)),
    to = rep(colnames(mat), each = nrow(mat)),
    value = as.vector(mat),
    stringsAsFactors = FALSE)
df

chordDiagram(mat)


filter(co_out, convergent) %>% 
  group_by(all_sample_clone_id) %>% 
  mutate(n = n(),
         id = str_c(SAMPLE, "_", all_sample_clone_id)) %>%
  select(id, SAMPLE, all_sample_clone_id, n) %>% 
  arrange(all_sample_clone_id) -> a


table(a$SAMPLE, a$all_sample_clone_id) %>% 
  as.matrix() -> a

chordDiagram(a)

a %*% t(a)
```

Add in cell cluster info

```{r}
co_out <- read_tsv(file.path(outdir, "vdj_new_clones.tsv.gz"))

library(Seurat)
source(here::here("R/utils.R"))
so <- readRDS("vdj_alone/objects_vdj_alone/so_w_vdj.rds")
all_cell_mdata <- get_metadata(so)

so <- readRDS("vdj_alone/objects_vdj_alone/bcells.rds")
b_cell_mdata <- get_metadata(so)

all_cell_mdata <- all_cell_mdata %>% 
  select(cell, cell_types) %>% 
  unique()

b_cell_mdata <- b_cell_mdata %>% 
  select(cell,fine_clusters) %>% 
  unique()

mdata <- left_join(all_cell_mdata, b_cell_mdata, by = c("cell"))
mdata <- rename(mdata, bcell_clusters = fine_clusters)

co_out <- left_join(co_out, mdata, by = c("cell_id" = "cell"))

co_out_summary <- mutate(co_out, 
                         cell_group = case_when(
                           cell_types != "B cell" ~ "Non-B-cell",
                           cell_types == "B cell" & bcell_clusters == "11" ~ "bcell_mzb1+",
                           cell_types == "B cell" & bcell_clusters == "4" ~ "bcell_cluster4",
                           cell_types == "B cell" ~ "bcell_other",
                           TRUE ~ "no expr"
                         ))
```

```{r}

co_out_sample <- group_by(co_out_summary, SAMPLE) %>% 
  arrange(desc(clone_size), 
          .by_group = TRUE) 
cos <- split(co_out_sample, co_out_sample$SAMPLE)
openxlsx::write.xlsx(cos, file.path(outdir, "vdj_clones_by_sample.xlsx"))

co_out_cluster <- group_by(co_out_summary, cell_group) %>% 
  arrange(desc(all_sample_clone_size), 
          .by_group = TRUE) 
cos <- split(co_out_cluster, co_out_cluster$cell_group)

openxlsx::write.xlsx(cos, file.path(outdir, "vdj_clones_by_cluster.xlsx"))

```

```{r}
write_tsv(co_out_summary, file.path(outdir, "vdj_new_clones_summary.tsv.gz"))

```


```{r}
co_out_summary <- read_tsv(file.path(outdir, "vdj_new_clones_summary.tsv.gz"))
to_plot_d <- c(
  "C_CALL"
)

to_plot_c <- co_out_summary %>% 
  select(CDR3_AA_LENGTH:CDR3_AA_AROMATIC) %>% 
  colnames()


p <- map(to_plot_d, 
    function(x) {
      xs <- sym(x)
      plt_dat <- co_out_summary
      plt_dat[[x]] <- ifelse(is.na(plt_dat[[x]]), 
                                  "none",
                                   plt_dat[[x]])
      
      ggplot(plt_dat, aes(cell_group)) +
      geom_bar(aes_string(fill = x), position = "fill") +
      scale_fill_brewer(name = x, 
                        palette = "Paired") +
      labs(x = "",
           y = "Proportion") +
      theme(axis.text.x = element_text(angle = 90,
                                       hjust = 1, 
                                       vjust = 0.5))
}) %>% 
  plot_grid(plotlist = .,
            nrow = 1,
            ncol = 1)

save_plot(file.path(fig_dir, "isotype_summary.pdf"), 
          p,
          nrow = 1,
          ncol = 1,
          base_asp = 1.2)


p <- map(to_plot_c, 
    function(x){
      ggplot(co_out_summary, aes_string("cell_group",
                                        x)) +
      geom_boxplot(aes(fill = cell_group), coef = 1e6) +
        scale_fill_brewer(palette = "Paired") +
        labs(x = "") +
        theme(legend.position = "none",
              axis.text.x = element_text(angle = 90,
                                       hjust = 1, 
                                       vjust = 0.5))
      }) %>% 
  plot_grid(plotlist = .,
            nrow = 3,
            ncol = 3)

save_plot(file.path(fig_dir, "aa_summary.pdf"), 
          p,
          nrow = 3,
          ncol = 3,
          base_asp = 0.75)
```

