---
title: "GEO"
author: "Kent Riemondy RBI"
date: "2/1/2021"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source(here::here("R/utils.R"))

dir.create("geo", showWarnings = FALSE)


```


## All cells 

```{r}
so <- qread(file.path("objects", "so_souped.qs"))

reid <- c(
  "HLAB6_2" = "HLAB6_1",
  "HLAB6_3" = "HLAB6_2",
  "HLAB6_5" = "HLAB6_3"
)

so$sample_id <- ifelse(so$orig.ident %in% names(reid),
                       reid[as.character(so$orig.ident)],
                       as.character(so$orig.ident))

rename_cell_types <- c(
  `alveolar macrophage` = "alveolar macrophage", 
  `B cell` = "B cell", 
  `B cell Mzb1+` = "plasma cell", 
  `classical monocyte` = "monocyte", 
  leukocyte = "leukocyte", 
  `lung endothelial cell` = "lung structural cell",
  `mast cell` = "mast cell",
  `myeloid cell` = "myeloid cell",
  `natural killer cell` = "natural killer cell", 
  `T cell` = "T cell", 
  `type II pneumocyte` = "Type 2 pneumocyte"
)
so$pub_cell_types <- rename_cell_types[so$cell_types]
so$pub_cell_types <- factor(so$pub_cell_types, 
                                levels = rename_cell_types)
so$cell_types_clusters <- str_c(so$pub_cell_types,
                                    " (",
                                    so$coarse_clusters,
                                    ")")

pub_cell_types_order <- so@meta.data[c("pub_cell_types",
                            "cell_types_clusters")] %>% 
  as_tibble() %>% 
  distinct() %>% 
  arrange(pub_cell_types) %>% 
  .[c(1:5, 10:15, 6:9), ] %>% 
  pull(cell_types_clusters)

pub_cell_types_cols <- discrete_palette_default[c(1:5, 7:9, 10, 10, 11, rep(6, 4))]


so$cell_types_clusters <- factor(so$cell_types_clusters, 
                                     levels = pub_cell_types_order)
```


```{r}
df_out <- as.data.frame(so@assays$RNA@counts) 
df_out <- rownames_to_column(df_out, "gene")
data.table::fwrite(x = df_out, 
                   file = "geo/count_matrix.tsv.gz",
                   sep = "\t",
                   compress = "gzip")
```

```{r}
all_cell_mdata <- so@meta.data %>% 
  rownames_to_column("cell")
```

```{r}
so <- qread(file.path("objects", "so_endo.qs"))

pub_cell_types <- c(
"0" = "MHC II+ endothelial cells",
"1" = "Epithelial cells",
"2" = "Epithelial cells",
"3" = "Fibroblasts and smooth muscle cells",
"4" = "Red blood cells",
"5" = "Vcam1+ endothelial cells",
"6" = "T cells",
"7" = "Epithelial cells",
"8" = "Krt8+ epithelial cells",
"9" = "Prox1+ endothelial cells",
"10" = "B cells"
)

so$pub_cell_types <- pub_cell_types[as.character(so$refined_clusters)]
so$cell_types_clusters <- str_c(so$pub_cell_types,
                               " (",
                               so$refined_clusters,
                               ")")

struct_cell_mdata <- so@meta.data %>% 
  rownames_to_column("cell") %>% 
  select(cell, 
         structural_cell_types = pub_cell_types,
         structural_cell_type_clusters = cell_types_clusters)
```

```{r}
b_cell_mdata <- qread(file.path("objects", "bcell_subclustering.qs")) %>%
  .@meta.data %>% 
  rownames_to_column("cell") %>% 
  select(cell, 
         b_cell_subpopulations = coarse_clusters)

```


```{r}
mdata <- select(all_cell_mdata,
       cell,
       sample_id,
       condition,
       all_cells_cell_type = pub_cell_types,
       all_cells_cell_type_cluster = cell_types_clusters) %>% 
  left_join(b_cell_mdata, by = "cell") %>% 
  left_join(struct_cell_mdata, by = "cell") 

write_tsv(mdata, "geo/meta-data.tsv.gz")
```

```{r}
tools::md5sum(c("geo/meta-data.tsv.gz",
                "geo/count_matrix.tsv.gz"))

```
